-- 코드를 입력하세요
SELECT f.CATEGORY,  ff.MAX_PRICE, f.PRODUCT_NAME
from FOOD_PRODUCT f
join (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
      FROM FOOD_PRODUCT
      WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
      GROUP BY CATEGORY
      ) ff
ON f.CATEGORY = ff.CATEGORY AND f.PRICE = ff.MAX_PRICE
ORDER BY f.PRICE DESC;
;
